SELECT * FROM TABELA_DE_CLIENTES;

SELECT NOME,
(CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'Clientes Grandes'
    WHEN LIMITE_DE_CREDITO < 150000 AND LIMITE_DE_CREDITO >= 110000 THEN 'Clientes Médios'
    ELSE 'Clientes Pequenos'
END) AS CLASSIFICACAO
FROM TABELA_DE_CLIENTES;