/*
listando uma Expressão NATURAL
- Quero construir um SQL cujo resultado seja, para cada cliente:
"O cliente NOME DO CLIENTE comprou QUANTIDADE no ano de ANO"
*/
---Consultando Tabelas Bases
SELECT * FROM TABELA_DE_CLIENTES;
SELECT * FROM ITENS_NOTAS_FISCAIS;
SELECT * FROM NOTAS_FISCAIS;
SELECT * FROM TABELA_DE_VENDEDORES;

--- Aplicando Consulta
SELECT 'O cliente ' || TC.NOME || ' comprou ' ||
TO_CHAR(ROUND(SUM(INF.QUANTIDADE * INF.PRECO),2)) || ' no ano de ' || TO_CHAR(DATA_VENDA, 'YYYY') AS SENTENCA
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC ON NF.CPF = TC.CPF
WHERE TO_CHAR(DATA_VENDA, 'YYYY') = '2016'
GROUP BY TC.NOME, TO_CHAR(DATA_VENDA, 'YYYY');