/*
TRABALHANDO COM VIEWS
*/
CREATE VIEW VW_SOMA_EMBALAGENS AS
SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

/*
CONSULTANDO A VIEW
*/
SELECT EMBALAGEM, SOMA_PRECO FROM VW_SOMA_EMBALAGENS
WHERE SOMA_PRECO >=80;

/*
INNER JOIN COM VIEW
*/
SELECT * FROM TABELA_DE_PRODUTOS TP
INNER JOIN VW_SOMA_EMBALAGENS VW
ON TP.EMBALAGEM = VW.EMBALAGEM
WHERE VW.SOMA_PRECO >= 80;




/* SUB CONSULTA */
SELECT SOMA_EMBALAGENS.EMBALAGEM, SOMA_EMBALAGENS.SOM_PRECO
FROM(SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM)
WHERE SOMA_EMBALAGENS.SOMA_PRECO >= 80;